name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 4 * * *'

jobs:
  industrial_ci:
    strategy:
      fail-fast: false
      matrix:
        env:
          - {CI_NAME: clang-format,
             OS_NAME: ubuntu,
             OS_CODE_NAME: bionic,
             ROS_DISTRO: eloquent,
             BADGE: bionic,
             CLANG_FORMAT_CHECK: file,
             CLANG_FORMAT_VERSION: 8,
             }
          - {OS_NAME: ubuntu,
             OS_CODE_NAME: bionic,
             ROS_DISTRO: eloquent,
             ROSDEP_SKIP_KEYS: nvidia-cuda-dev,
             BADGE: bionic,
             UPSTREAM_CMAKE_ARGS: "-DCMAKE_LIBRARY_PATH=/usr/local/cuda/lib64/stubs/",
             UPSTREAM_WORKSPACE: 'github:ros-industrial/yak#devel github:schornakj/gl_depth_sim#feature/pure-cmake',
             TARGET_CMAKE_ARGS: "-DBUILD_DEMO=True",
             DOCKER_PULL: false,
             DOCKER_IMAGE: "schornakj/yak-1:eloquent-cuda10.2",
             }
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
